import assert from "node:assert/strict";
import {makeCoalescer,toolSummary,toolLabel,toolKind} from "../web/xr-hud.js";
const co=makeCoalescer();
const ev=(k,text)=>co.event({sessionUpdate:k,content:{type:"text",text}});
ev("user_message_chunk","[AGENT SETUP — follow for this session] PERSONA: Rikku");
ev("user_message_chunk","list my files");
for(const c of ["Rao, ","sure ","thing."])ev("agent_message_chunk",c);
for(const c of ["Need to ","list the dir."])ev("agent_thought_chunk",c);
co.event({sessionUpdate:"tool_call",toolCallId:"t1",title:"read_file",status:"in_progress",rawInput:{target_file:"C:\\\\Users\\\\antho\\\\x.py"}});
co.event({sessionUpdate:"tool_call_update",toolCallId:"t1",status:"completed"});
for(const c of ["Fourteen ","files."])ev("agent_message_chunk",c);
const kinds=co.turns.map(t=>t.kind);
assert.deepEqual(kinds,["sys","you","her","think","tool","her"],"one row per turn, not per chunk");
assert.equal(co.turns[2].body,"Rao, sure thing.");
assert.equal(co.turns[3].n,2);
const tool=co.turns[4];
assert.equal(tool.meta.status,"completed","tool update folds into the same row");
assert.equal(tool.body,"C:\\Users\\antho\\x.py","summary unescapes the path and shows no JSON");
assert.equal(co.turns.filter(t=>t.kind==="tool").length,1);
assert.equal(toolLabel({title:"Read `C:\\x\\y.py`"}),"Read");
assert.equal(toolKind({title:"Web search: foo"}),"read");
assert.equal(toolKind({title:"Edit file"}),"write");
assert.equal(toolSummary({rawInput:JSON.stringify({command:"ls -la  ./x"})}),"ls -la ./x");
assert.ok(toolSummary({rawInput:{query:"a".repeat(200)}}).length<=96);
const co3=makeCoalescer();for(const c of ["[You are in the room with Anthony ","as a hologram.] ","Read the file"])co3.event({sessionUpdate:"user_message_chunk",content:{text:c}});
assert.deepEqual(co3.turns.map(t=>t.kind),["sys","you"],"chunked primer stays one setup row, the prompt after it is one you row");assert.equal(co3.turns[1].body,"Read the file");
co3.event({sessionUpdate:"user_message_chunk",content:{text:"Read the file"}});assert.equal(co3.turns.length,2,"echo of the same prompt dedupes");
console.log("xr-hud ok");
