import assert from "node:assert/strict";
import {addressed,makeBudget,situation,REFLEX,DELIBERATE,motionScore} from "../web/xr-senses.js";
const names=["rikku","hey you"];
let a=addressed("Rikku, what time is it?",names);
assert.equal(a.hit,true);assert.equal(a.text,"what time is it");
a=addressed("so I told him about the rikku thing",names);
assert.equal(a.hit,true);assert.equal(a.text,"thing");
a=addressed("the build is failing again",names);
assert.equal(a.hit,false);
a=addressed("hey you, look at this",names);
assert.equal(a.hit,true);assert.equal(a.text,"look at this");
const b=makeBudget({minGapMs:1000,maxPerHour:3});
assert.equal(b.ok(0),true);b.spend(0);
assert.equal(b.ok(500),false,"min gap holds");
assert.equal(b.ok(1000),true);b.spend(1000);b.spend(2000);
assert.equal(b.ok(5000),false,"hourly cap holds");
assert.equal(b.ok(3600001+2000),true,"cap slides after an hour");
const env={clock:"09:12",foreground:{title:"server.py - Cursor"},work:{running:1,running_titles:["Fix rail"],just_finished:["Old"],open_asks:[],latest_tool:null}};
const s=situation({type:"arrive"},env,{overheard:["dinner at six"]});
assert.match(s,/came into view/);assert.match(s,/server\.py - Cursor/);assert.match(s,/1 agent job running/);assert.match(s,/dinner at six/);assert.match(s,/\[\[quiet\]\]/);
assert.match(situation({type:"work_done"},env,{}),/Old/);
for(const k of Object.keys(REFLEX))for(const [kind] of REFLEX[k])assert.ok(kind==="gaze"||kind==="motion");
assert.ok(DELIBERATE.has("arrive")&&!DELIBERATE.has("focus_change"),"focus changes never trigger speech");
const w=4,h=1,prev=new Uint8ClampedArray(16).fill(0),cur=new Uint8ClampedArray(16).fill(30);
assert.equal(motionScore(prev,cur,w,h),90);assert.equal(motionScore(null,cur,w,h),0);
console.log("xr-senses ok");
