const fs=require("fs"),path=require("path"),vm=require("vm");
const src=fs.readFileSync(path.join(__dirname,"..","web","md.js"),"utf8");
const ctx={console:console};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(src,ctx);
const md=ctx.md;
let pass=0,fail=0;
const t=(name,input,checks)=>{
 let out;
 try{out=md(input)}catch(e){console.log("FAIL "+name+" THREW "+e.message);fail++;return}
 const bad=checks.filter(c=>c[0]==="has"?out.indexOf(c[1])<0:out.indexOf(c[1])>=0);
 bad.length?(fail++,console.log("FAIL "+name),console.log("   out: "+out),bad.forEach(c=>console.log("   want "+c[0]+" "+JSON.stringify(c[1])))):pass++;
};
t("blockquote",  "> line one\n> line two",[["has","<blockquote>"],["no","&gt;"]]);
t("blockquote_nested_md","> **bold** quote",[["has","<blockquote>"],["has","<strong>bold</strong>"]]);
t("table_no_outer_pipes","Name | Role\n--- | ---\nClaude | coder",[["has","<table>"],["has","<th>Name</th>"],["has","<td>Claude</td>"]]);
t("table_at_end_no_nl","| A | B |\n| --- | --- |\n| 1 | 2 |",[["has","<td>1</td>"],["has","<td>2</td>"],["no","| 1 |"]]);
t("table_align","| A | B |\n|:--|--:|\n| 1 | 2 |",[["has","text-align:left"],["has","text-align:right"]]);
t("ordered_paren","1) first\n2) second",[["has","<ol>"],["has","<li>first</li>"],["no","1)"]]);
t("ordered_start","3. third\n4. fourth",[["has",'<ol start="3">']]);
t("task_list","- [ ] todo\n- [x] done",[["has","type=\"checkbox\""],["has","checked"],["no","[ ]"],["no","[x]"]]);
t("tilde_fence","~~~python\nprint(1)\n~~~",[["has","<pre>"],["has","hl-fn"],["no","<s>"]]);
t("backtick_fence","```js\nlet a=1;\n```",[["has","<pre>"],["has","hl-kw"]]);
t("unclosed_fence","Here:\n```python\nprint(1)",[["has","<pre>"],["no","```"]]);
t("text_after_hr","---\n**after**",[["has","<hr>"],["has","<strong>after</strong>"],["no","**after**"]]);
t("text_after_list","- a\n- b\n\nnot a bullet",[["has","<ul>"],["has","<p>not a bullet</p>"]]);
t("no_ul_inside_p","intro\n\n- a\n- b\n\noutro",[["has","<p>intro</p>"],["has","<ul>"],["no","<p>intro</p><ul>".replace("</p>","")]]);
t("nested_list","- top\n  - child\n- top2",[["has","<li>top<ul><li>child</li></ul></li>"]]);
t("heading_levels","# H1\n## H2\n### H3",[["has","<h1>H1</h1>"],["has","<h2>H2</h2>"],["has","<h3>H3</h3>"]]);
t("bare_url","see https://example.com for more",[["has",'href="https://example.com"']]);
t("md_link","[docs](https://x.io/a)",[["has",'href="https://x.io/a"'],["has",">docs</a>"]]);
t("no_js_url","[click](javascript:alert(1))",[["no",'href="javascript:']]);
t("setext_stays_hr","Some heading\n---\ntext",[["has","<hr>"],["no","<table>"]]);
t("snake_case","call foo_bar_baz and my_var here",[["has","foo_bar_baz"],["no","<em>"]]);
t("bold_italic","This is ***very*** ok",[["has","<strong><em>very</em></strong>"]]);
t("indented_code","    def f():\n        return 1",[["has","<pre><code>"],["has","def f():"]]);
t("inline_code_pipe","use `a | b` here",[["has","<code>a | b</code>"],["no","<table>"]]);
t("html_escaped","<script>alert(1)</script>",[["no","<script>"],["has","&lt;script&gt;"]]);
t("code_span_no_em","`a *b* c`",[["has","<code>a *b* c</code>"],["no","<em>"]]);
t("hard_break","line one  \nline two",[["has","<br>"]]);
t("table_then_text","| A |\n| --- |\n| 1 |\n\nafter",[["has","<td>1</td>"],["has","<p>after</p>"]]);
t("fence_in_list","- item\n\n```js\nlet a=1;\n```",[["has","<ul>"],["has","<pre>"]]);
t("adjacent_lists_ul_then_ol","- a\n- b\n\n1) one\n2) two",[["has","<ul>"],["has","<ol>"],["has","<li>a</li>"],["has","<li>one</li>"],["has","<li>two</li>"]]);
t("adjacent_lists_ol_then_task","1. one\n\n- [ ] task",[["has","<ol>"],["has","<li>one</li>"],["has","checkbox"]]);
t("nested_then_other_list","- top\n  - kid\n- top2\n\n1) num",[["has","<li>kid</li>"],["has","<li>top2</li>"],["has","<li>num</li>"]]);
t("currency_does_not_open_math","at **-$9.87** (3 capped losses of -$3.29), followed by **JPM at -$9.26**.",
  [["has","<strong>-$9.87</strong>"],["has","<strong>JPM at -$9.26</strong>"],["no","katex"],["no","rawmath"],["no","**"]]);
t("plain_money_pairs","costs $10 and $20 total",[["has","costs $10 and $20 total"],["no","rawmath"]]);
t("escaped_dollar_loses_backslash","under L=\\$3.29, the \\$25 cap",[["has","L=$3.29"],["has","the $25 cap"],["no","\\$"]]);
t("escaped_dollar_inside_math","$L=\\$3.29$",[["has","rawmath"],["has","L=\\$3.29"]]);
t("math_still_works","on $n = 65$ live trades",[["has","rawmath"],["has","n = 65"]]);
t("superscript_math","$x^2 + y^2 = z^2$ holds",[["has","rawmath"],["has","x^2"]]);
t("display_math","$$E = mc^2$$",[["has","rawmath"],["has","E = mc^2"]]);
t("dollar_in_code_fence","```py\nx = $5\n```",[["has","$5"],["no","rawmath"]]);
t("dollar_in_code_span","use `$5` here",[["has","<code>$5</code>"],["no","rawmath"]]);
t("ws_image_stays_literal","see ![chart](chart.png)",[["has","![chart](chart.png)"],["no","<img"]]);
t("remote_image","![x](https://a.io/b.png)",[["has",'src="https://a.io/b.png"']]);
t("ws_file_link_not_special","grab [the csv](results.csv)",[["no","/api/files"],["has","path-link"],["has","results.csv"],["no","[the csv](results.csv)"]]);
t("no_traversal_scheme","![x](javascript:alert(1))",[["no","<img"]]);
t("dotdot_not_linked","[x](../../etc/passwd)",[["no","href"]]);
t("empty",""  ,[["no","undefined"]]);
console.log("\n"+pass+" passed, "+fail+" failed");
process.exit(fail?1:0);
